workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.pcpeli.rrhh
      groups:
        - appstore_credentials
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Add iOS platform
        script: |
          npx cap add ios || true
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
      - name: Auto-increment build number
        script: |
          LATEST=$(app-store-connect get-latest-testflight-build-number com.pcpeli.rrhh 2>/dev/null || echo "1")
          echo "Latest TestFlight build: $LATEST"
          NEW_BUILD=$((LATEST + 1))
          echo "Setting new build number to: $NEW_BUILD"
          
          PLIST="$CM_BUILD_DIR/ios/App/App/Info.plist"
          PBXPROJ="$CM_BUILD_DIR/ios/App/App.xcodeproj/project.pbxproj"
          
          # Update Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" "$PLIST"
          
          # Update CURRENT_PROJECT_VERSION in pbxproj
          sed -i '' "s/CURRENT_PROJECT_VERSION = [0-9]*;/CURRENT_PROJECT_VERSION = $NEW_BUILD;/g" "$PBXPROJ"
          
          # Update MARKETING_VERSION if needed
          sed -i '' "s/MARKETING_VERSION = [0-9.]*;/MARKETING_VERSION = 1.0.$NEW_BUILD;/g" "$PBXPROJ"
          
          # Verify changes
          echo "=== Info.plist CFBundleVersion ==="
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST"
          echo "=== pbxproj CURRENT_PROJECT_VERSION ==="
          grep "CURRENT_PROJECT_VERSION" "$PBXPROJ" | head -5
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
