workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.pcpeli.rrhh
      groups:
        - appstore_credentials
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Add iOS platform
        script: |
          npx cap add ios || true
          npx cap sync ios
      - name: Auto-increment build number
        script: |
          cd ios/App
          LATEST=$(app-store-connect get-latest-testflight-build-number com.pcpeli.rrhh 2>/dev/null || echo "1")
          echo "Latest TestFlight build: $LATEST"
          NEW_BUILD=$((LATEST + 1))
          echo "Setting new build number: $NEW_BUILD"
          agvtool new-version -all $NEW_BUILD
          # Also set via PlistBuddy as fallback
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" App/Info.plist || true
          echo "Build number confirmed: $NEW_BUILD"
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
