// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Capacitor } from '@capacitor/core';
import { capacitorStorage } from '@/lib/capacitorStorage';

const SUPABASE_URL = "https://srfigyjdkbwzkuddndvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyZmlneWpka2J3emt1ZGRuZHZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjA4NjksImV4cCI6MjA3MzU5Njg2OX0.cL1pv2GKWhvYqV5dXV5_FTpqq2H60GIdqqnw-mIiyRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use Capacitor Preferences for mobile, localStorage for web
const storage = Capacitor.isNativePlatform() ? capacitorStorage : localStorage;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: storage as any,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Important for mobile apps
  }
});